# Generated by Django 4.2.2 on 2024-02-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='ID Telegram')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Name')),
            ],
            options={
                'verbose_name': 'Bot User',
                'verbose_name_plural': 'Bot Users',
            },
        ),
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creates_join_request', models.BooleanField(default=False, verbose_name='Request to add')),
                ('creator', models.CharField(blank=True, max_length=250, null=True, verbose_name='Creator')),
                ('expire_date', models.CharField(blank=True, max_length=150, null=True, verbose_name='Expire date')),
                ('invite_link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Invite link')),
                ('is_primary', models.CharField(blank=True, max_length=150, null=True, verbose_name='Is primary')),
                ('is_revoked', models.BooleanField(blank=True, null=True, verbose_name='Is revoked')),
                ('member_limit', models.IntegerField(blank=True, null=True, verbose_name='Subscription limit')),
                ('link_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Link name')),
                ('pending_join_request_count', models.CharField(blank=True, max_length=150, null=True, verbose_name='Pending join request count')),
            ],
            options={
                'verbose_name': 'Invite link',
                'verbose_name_plural': 'Invite links',
            },
        ),
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='ID Telegram')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Name')),
                ('subscribed', models.BooleanField(default=False, verbose_name='Subscribed')),
                ('datetime_subscribe', models.DateTimeField(blank=True, null=True, verbose_name='Subscription date')),
                ('datetime_unsubscribe', models.DateTimeField(blank=True, null=True, verbose_name='Unsubscription date')),
                ('invite_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.invitelink', verbose_name='Invite link')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Channel name')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser', verbose_name='Bot User')),
            ],
            options={
                'verbose_name': 'Channel chat',
                'verbose_name_plural': 'Channels chats',
            },
        ),
        migrations.AddField(
            model_name='invitelink',
            name='telegram_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramchat', verbose_name='Channel chat'),
        ),
    ]
